### ISSUE TITLE
Fix getAll method to return the correct value for StringSet.

### ISSUE THREAD

**Issue by footyapps27** [scottyab/secure-preferences#100]
The current implementation of getAll returns hashed keys & decrypted values (as Strings).

However, it does not return values correctly when the stored type is a Set<String>.

For migration to Android Q, it is important that we get all the decrypted values that are stored in the list & migrate using our own salt.

**Comment by footyapps27** [comment]
I have created a PR #99 to fix this issue.
Please considering merging the same & making a new release.

**Comment by scottyab** [comment]
Thanks @footyapps27, you're a ⭐️
