### ISSUE TITLE
Security scan fail

### ISSUE THREAD

**Issue by Dnyanoba-Kantode** [scottyab/secure-preferences#11]
Hi Scott,

After security scan by our tool this lib get failed because follows threat is found.

Description: This cryptographic object is initialized with the cipher spec 'AES', which uses the known risky ECB cipher mode. Because ECB encrypts each block of plaintext independently, the resulting ciphertext is susceptible to dictionary attacks.
Remediation: Use CBC or CTR mode instead. Consult the cryptographic literature to determine which mode is appropriate for your use case.

Thanks,
Dan

**Comment by scottyab** [comment]
Thanks Dan, I'll look into

**Comment by scottyab** [comment]
So... i did include the stronger algorithms https://github.com/scottyab/secure-preferences/blob/master/library/src/com/securepreferences/SecurePreferences.java#L68, namely AES/CBC/PKCS5Padding and prefered AES-GCM however ran in some issues on older devices not having them available. I'll change to default to AES/CBC/PKCS5Padding but maintain backwards compatibility add an option to use default 'AES'

**Comment by Dnyanoba-Kantode** [comment]
Thank you very much scott. I will look into it.

**Comment by scottyab** [comment]
fixed in v0.1.0
