### ISSUE TITLE
Put v0.1.0 on maven central

### ISSUE THREAD

**Issue by cartierjf** [scottyab/secure-preferences#13]
Only 0.0.4 is available with gradle

**Comment by scottyab** [comment]
Yes, you're right, published this morning and also tagged and uploaded aar to github releases. Will close this once changes are propagated to all servers.

**Comment by cartierjf** [comment]
it's available on maven central now. You can update your doc in confidence and then you're good to close this issue!

**Comment by jitpack-io** [comment]
Btw, guys, it's also very easy to get the latest GitHub release with JitPack.io. No need to upload anything. Here's v0.1.0: https://jitpack.io/#scottyab/secure-preferences/v0.1.0 : )

**Comment by aldur** [comment]
Even if v0.1.0 is on Maven Central, how do you handle [aes-crypto](https://github.com/scottyab/java-aes-crypto) dependency?
I end up getting: `Could not find com.scottyab:aes-crypto:0.0.2-SNAPSHOT.`

**Comment by Laimiux** [comment]
For time being, add 
repositories {
    maven {
        url "https://oss.sonatype.org/content/repositories/snapshots"
    }
}
and
dependencies {
    // Secured preferences
    compile 'com.scottyab:aes-crypto:0.0.2-SNAPSHOT'
    compile('com.scottyab:secure-preferences-lib:0.1.0') {
        provided 'com.scottyab:aes-crypto:0.0.2-SNAPSHOT'
    }
}

**Comment by scottyab** [comment]
Apologies chaps, I'll sort that aes-crypto dependancy soon. It's my fork and I was waiting for the repo owner to accept my PR.

**Comment by gabrielacosta** [comment]
Thank you Laimiux for your answer. Scott nice library, I think you should put Laimiux answer in the main page, because, most of us are using graddle and it will be easy meanwhile you sort the issues with the dependencies.

**Comment by scottyab** [comment]
Hey @gabrielacosta, done, but i'll need to go one better and sort it properly and remove the snapshot repo dependancy. I will just publish my fork to Maven Central as aes-crypto owner doesn't seem to have done that yet (even thought they have accepted my PR).

**Comment by scottyab** [comment]
This is all sync'd up correctly in v0.1.1 

`compile 'com.scottyab:secure-preferences-lib:0.1.1`
