### ISSUE TITLE
Could not find com.scottyab:aes-crypto:0.0.2-SNAPSHOT

### ISSUE THREAD

**Issue by gabrielacosta** [scottyab/secure-preferences#19]
Hi Scott,

I was using your library with this configuration in Graddle.

compile 'com.scottyab:aes-crypto:0.0.2-SNAPSHOT'
    compile('com.scottyab:secure-preferences-lib:0.1.0') {
        provided 'com.scottyab:aes-crypto:0.0.2-SNAPSHOT'
    }

It was working fine until last week. I got an error that aes-crypto:002-SNAPSHOT cannot be found.

Could you please check this.

Kind regards,

G

**Comment by scottyab** [comment]
Hey, I've fixed/removed the dependancy on the SNAPSHOT repo, please use  

`compile 'com.scottyab:secure-preferences-lib:0.1.1'`

**Comment by IgorGanapolsky** [comment]
I am having the same issue now.  `compile 'com.scottyab:secure-preferences-lib:0.1.1'`.  Please advise!

**Comment by scottyab** [comment]
Hi @IgorGanapolsky,  Just to confirm `compile 'com.scottyab:aes-crypto:0.0.2-SNAPSHOT'` has been promoted to production repo. So omit the -SNAPSHOT. 
  
But for Secure Preferences please remove the previous config:

`compile 'com.scottyab:aes-crypto:0.0.2-SNAPSHOT'
compile('com.scottyab:secure-preferences-lib:0.1.0') {
provided 'com.scottyab:aes-crypto:0.0.2-SNAPSHOT'
}`

replaced with 
`compile 'com.scottyab:secure-preferences-lib:0.1.1'`

If you're still having issue, please post your build.gradle file/error log etc. Thanks

**Comment by IgorGanapolsky** [comment]
0.1.1 works, thanks.

**Comment by scottyab** [comment]
ok great, i think this is the same issue @gabrielacosta is having.
