### ISSUE TITLE
putStringSet Throws error

### ISSUE THREAD

**Issue by BhimAle** [scottyab/secure-preferences#20]
While I use  editor.putString it is working well , 
but when I tried to use  editor.putStringSet, app crashes giving following error :

     Caused by: java.lang.ClassCastException: java.util.HashMap cannot be cast to java.lang.String.

I am adding Arraylist in set. It works well if I donot try to encrypt the data. Gives error if I use it.

Am I missing something.
THank YOu

**Comment by scottyab** [comment]
Hey @BhimAle, Sorry to hear you're seeing an issue. I've just written a [unit test](https://github.com/scottyab/secure-preferences/commit/b7d79d794ce14a7bce84671c29fb75a350eaf327) for test the putStringSet and it seems to pass aok. 

When you say "It works well if I donot try to encrypt the data."  Are you saying your using the same pref file for encrypted and non-encrpyted values if not that's **not** recommended. Does this still happen if you clear the data of the app?

**Comment by scottyab** [comment]
Cannot recreate, closing until more info.
