### ISSUE TITLE
Static SharedPreferences field

### ISSUE THREAD

**Issue by pivotal-csaa-dev** [scottyab/secure-preferences#22]
Due to the SharedPreferences field value in SecurePreferences it is impossible to have multiple secure preference files. This also causes issues when running Robolectric tests. We saw test pollution when we tried to inject a new instance of SecurePreferences for each test example that depended on one.

**Comment by scottyab** [comment]
OMG, yes this is an issue. It seems so obvious now it’s been pointed out, Thanks.

**Comment by scottyab** [comment]
Fixed in  0.1.2
