### ISSUE TITLE
Proguard compatibility

### ISSUE THREAD

**Issue by cermakcz** [scottyab/secure-preferences#29]
Today I stumbled upon an issue with Proguard. 

The [AesCbcWithIntegrity](https://github.com/scottyab/java-aes-crypto/blob/master/aes-crypto/src/main/java/com/tozny/crypto/android/AesCbcWithIntegrity.java) class from aes-crypto lib contains the [PrngFixes](https://github.com/scottyab/java-aes-crypto/blob/master/aes-crypto/src/main/java/com/tozny/crypto/android/AesCbcWithIntegrity.java#L666) inner class, which in turn contains [LinuxPRNGSecureRandom](https://github.com/scottyab/java-aes-crypto/blob/master/aes-crypto/src/main/java/com/tozny/crypto/android/AesCbcWithIntegrity.java#L817) and [LinuxPRNGSecureRandomProvider](https://github.com/scottyab/java-aes-crypto/blob/master/aes-crypto/src/main/java/com/tozny/crypto/android/AesCbcWithIntegrity.java#L799) inner classes. Then the class returned from SecureRandom.getProvider() is compared with simple equals on its simple name with the string "LinuxPRNGSecureRandomProvider" [here](https://github.com/scottyab/java-aes-crypto/blob/master/aes-crypto/src/main/java/com/tozny/crypto/android/AesCbcWithIntegrity.java#L758).

When Proguard changes the names of these inner classes to some non-sense, the comparison won't, of course, work.

My proposed fix is to mention correct Proguard rules in README.md. This works for me:

    -keep class com.tozny.crypto.android.AesCbcWithIntegrity$PrngFixes$* { *; }

**Comment by scottyab** [comment]
Thanks @cermakcz I'll add to the readme

**Comment by scottyab** [comment]
No specific ProGuard/DexGuard config is need to get v0.1.4 working.
