### ISSUE TITLE
handlePasswordChange problems (v0.1.4)

### ISSUE THREAD

**Issue by zecatman** [scottyab/secure-preferences#41]
Consider the following code snippet 

    SecurePreferences securedPreferences = new SecurePreferences(myContext, "myPassword", "myfile");
    securedPreferences.handlePasswordChange("myNewPassword", myContext);

Using handlePasswordChange leads to a strange behaviour. After method call, secured preferences file myfile.xml is empty and updated preferences are written into default shared preferences file.

Problem seems to come from the following method

    private SharedPreferences getSharedPreferenceFile(Context context, String prefFilename) {
            this.sharedPrefFilename = sharedPrefFilename ;

            if(TextUtils.isEmpty(prefFilename)) {
                return PreferenceManager
                        .getDefaultSharedPreferences(context);
            }
            else{
              return context.getSharedPreferences(prefFilename, Context.MODE_PRIVATE);
            }
    }

It does not set sharedPrefFilename attribute with parameter prefFilename. So it is null when handlePasswordChange uses it to handle shared preference instance refresh

    //refresh the sharedPreferences object ref: I found it was retaining old ref/values
    sharedPreferences = null;
    sharedPreferences = getSharedPreferenceFile(context, sharedPrefFilename);

**Comment by scottyab** [comment]
Thanks for reporting, this was fixed in PR#42
