### ISSUE TITLE
Allow to provide own salt instead of deprecated ANDROID_ID 

### ISSUE THREAD

**Issue by tprochazka** [scottyab/secure-preferences#54]
Depend on ANDROID_ID is really not good idea, it is deprecated by Google and it can change on some crap devices for example during Android update and user will lost it's data. It is also not good idea if you want to allows to backup preferences and restore it on the new user device.

I know that I can provide completely own  SecretKeys, but it is too much complicated.

Maybe some builder for preferences would be much better than too much constructor parameters.

**Comment by scottyab** [comment]
Good idea. Thanks for raising.

**Comment by scottyab** [comment]
merged #67 Thanks for issue and PR
