### ISSUE TITLE
Question about license and using strong encryption outside of USA

### ISSUE THREAD

**Issue by bogdanRada** [scottyab/secure-preferences#56]
I am working on a Android application that i want to release to be available for customers from both USA and Romania. Does this library require a special license for using strong encryption? The reason why i ask this is because some other libraries like SQLCIpher for Android require special license for this ( according to this blog http://www.informit.com/articles/article.aspx?p=2268753&seqNum=3 )

I was wondering if this is the case for this too. Please let me know. Thank you very much.

**Comment by scottyab** [comment]
Good question!, and I'm defo not lawyer so to cover all the bases I'd advise seeking professional advice. That said secure-preferences doesn't use any additional algorthms that aren't already part of Android. So if Android is ok to be exported, so to it secure-preference lib.  Hope this helps.

**Comment by bogdanRada** [comment]
Hmm, well this library depends on this https://github.com/scottyab/java-aes-crypto. And i am not sure if this requires special license for encryption. And since there is no posibility to open an issue there to ask this question, i opened it here. Do you know if that library is using strong encryption? and if there is a need for a special license?

**Comment by bogdanRada** [comment]
I opened a issue on the original repo too https://github.com/tozny/java-aes-crypto/issues/31 , but since your repository is a derivative work, i am a bit confuse. ANy help would be greatly appreciated. Thanks

**Comment by scottyab** [comment]
Ah yes, I think my above answer still stands. java-aes-crypto uses `AES` and `PBKDF2WithHmacSHA1` both of which are part of Andorid.

**Comment by bogdanRada** [comment]
Well then, i guess there is no need for special license. I though maybe your library includes other types of algorithms. Thanks a lot. Saved my day :)
