### ISSUE TITLE
How to decrypt shared pref key

### ISSUE THREAD

**Issue by barryjohncoronel** [scottyab/secure-preferences#69]
When i was trying to use SharedPreferences.getAll(), I am getting the encrypted key = actual value(e.g E9hgkasdjafuyg3X = false)

How to get the actual key also? Thanks.

**Comment by scottyab** [comment]
Hey @barryjohncoronel, SecurePreferences handles the encryption and decryption under the hood so you shouldn't need the key.

**Comment by spff** [comment]
I don't think so. You are hashing the key instead of encrypting it.
This might make users need to hashPrefKey in the switch case when setting up a listener.
