### ISSUE TITLE
Build.SERIAL is deprecated in SDK 26 and will return UNKNOWN

### ISSUE THREAD

**Issue by patrickfav** [scottyab/secure-preferences#72]
Referencing this code

```
String deviceSerial = (String) Build.class.getField("SERIAL").get(
                    null);
```

Since SDK 26, `Build.SERIAL` is deprecated and will NOT return the device's serial number. This makes it will make it non-compatible. Since SDK 26 one should use `Build.getSerial()` which requires the PHONE permission.

https://developer.android.com/reference/android/os/Build.html#getSerial()

This will probably make the encrypted data non forward compatible when a device is upgraded to SDK 26.

**Comment by scottyab** [comment]
Thanks for raising this @patrickfav I'm in the middle of update that moves the code which gets the Serial more to the ownership of the implementing developer.

**Comment by patrickfav** [comment]
@scottyab I see, handling all the physical ids can be pretty annoying :) The upside is that Android_ID will be unique per App from SDK25 on (or 26?) so this might be a better salt than device serial anyways. Btw for pinning the data I also like to use the sha hash of the apk signature.

**Comment by ragazenta** [comment]
Should we use compileSdkVersion 25 if we use `v0.1.4`? Or is it okay if we use compileSdkVersion 26?

@scottyab Will you release #67 to Maven? It has additional salt parameter in constructor.

**Comment by scottyab** [comment]
This is released. Thanks for rasing this .
