### ISSUE TITLE
Create tag 0.1.7

### ISSUE THREAD

**Issue by franmontiel** [scottyab/secure-preferences#86]
There was a bug on 0.1.6 that has been solved but there is no release of a new version and we need to rely on -SNAPSHOT to use the dependency (as for some reason the build of a particular commit do not work on JitPack).

If you can create a tag for this bugfix we can avoid relying on SNAPSHOT builds that can make our app prone to failure due to future changes.

Thanks for your great work with the library

**Comment by scottyab** [comment]
Done #94 Thanks for the feedback
